### ISSUE TITLE
Indexing is really slow

### ISSUE THREAD

**Issue by legaultmarc** [legaultmarc/genometools#5]
The `db.index` module needs to be looked at. It took a long time to index multi-chromosome files.

**Comment by lemieuxl** [comment]
I think it's related to "not numerical" chromosomes (_e.g._ X, Y, MT).

**Comment by legaultmarc** [comment]
Let's drop the db.index module and replace it with compatibility with tabix. https://github.com/slowkow/pytabix

**Comment by legaultmarc** [comment]
I ended up rewriting the indexing algorithm. It now works a lot better, but it is not compatible with older versions.
